events {}

http {
    upstream django {
        server django_app:8000;
    }

    upstream fastapi {
        server fastapi_app:8001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ai/ {
            proxy_pass http://fastapi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
