"""
backend/shared/__init__.py
Shared core constants, enums, and types across Django and FastAPI services.
"""
from .constants import (
    PROJECT_NAME,
    DEFAULT_PAGE_SIZE,
    DEFAULT_LLM_MODEL,
    DEFAULT_LLM_TEMPERATURE,
    FORBIDDEN_TERMS,
    SAFETY_WARNING_MESSAGE,
    INTENT_ASSIGNMENT_KEYWORDS,
    INTENT_QUIZ_KEYWORDS,
    INTENT_PLANNER_KEYWORDS,
    INTENT_MATH_OPERATORS,
    INTENT_MATH_KEYWORDS,
    INTENT_KNOWLEDGE_KEYWORDS,
    INTENT_NODE_MAPPING,
)
from .enums import UserRole

__all__ = [
    "PROJECT_NAME",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_LLM_TEMPERATURE",
    "FORBIDDEN_TERMS",
    "SAFETY_WARNING_MESSAGE",
    "INTENT_ASSIGNMENT_KEYWORDS",
    "INTENT_QUIZ_KEYWORDS",
    "INTENT_PLANNER_KEYWORDS",
    "INTENT_MATH_OPERATORS",
    "INTENT_MATH_KEYWORDS",
    "INTENT_KNOWLEDGE_KEYWORDS",
    "INTENT_NODE_MAPPING",
    "UserRole",
]
