import type {
  ContinueLearningCourse,
  LiveClassItem,
  AssignmentItem,
} from '../types/dashboard.types';
import type { RegisteredCourseItem } from '../types/courses.types';
import type { ScheduleItem } from '../types/schedule.types';

export const DEFAULT_CONTINUE_LEARNING: ContinueLearningCourse = {
  id: 'c1',
  title: 'Artificial Intelligence & Deep Learning (AI)',
  chapter: 'Chapter 4: Neural Networks & Transformer Architectures',
  progressPercent: 68,
};

export const DEFAULT_REGISTERED_COURSES: RegisteredCourseItem[] = [
  {
    id: 'rc1',
    title: 'Introduction to Computer Science & Software Engineering',
    subjectField: 'Computer Science (CS)',
    courseCode: 'CS-101',
    creditHours: 4,
    progressPercent: 75,
    completedLessons: 12,
    totalLessons: 16,
    enrolledDate: 'Jan 10, 2026',
    status: 'active',
  },
  {
    id: 'rc2',
    title: 'Data Structures, Algorithms & Problem Solving',
    subjectField: 'Computer Science (CS)',
    courseCode: 'CS-201',
    creditHours: 4,
    progressPercent: 60,
    completedLessons: 9,
    totalLessons: 15,
    enrolledDate: 'Jan 15, 2026',
    status: 'active',
  },
  {
    id: 'rc3',
    title: 'Database Management Systems & SQL Architecture',
    subjectField: 'Information Technology (IT)',
    courseCode: 'IT-305',
    creditHours: 3,
    progressPercent: 40,
    completedLessons: 6,
    totalLessons: 15,
    enrolledDate: 'Jan 20, 2026',
    status: 'active',
  },
  {
    id: 'rc4',
    title: 'Artificial Intelligence & Neural Network Models',
    subjectField: 'Artificial Intelligence (AI)',
    courseCode: 'AI-402',
    creditHours: 3,
    progressPercent: 68,
    completedLessons: 10,
    totalLessons: 15,
    enrolledDate: 'Feb 01, 2026',
    status: 'active',
  },
];

export const DEFAULT_SCHEDULE_ITEMS: ScheduleItem[] = [
  {
    id: 's1',
    title: 'Data Structures & Algorithms - Weekly Lecture',
    subject: 'Computer Science (CS)',
    timeFormatted: '09:00 AM - 10:30 AM',
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    timeSlot: '09:00 AM - 10:30 AM',
    dayOfWeek: 'Monday',
    instructorName: 'Dr. Aris Thorne',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Virtual Hall A-101',
    status: 'live',
  },
  {
    id: 's2',
    title: 'Object-Oriented Software Design (Java & C++)',
    subject: 'Software Engineering (SE)',
    timeFormatted: '11:00 AM - 12:30 PM',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    timeSlot: '11:00 AM - 12:30 PM',
    dayOfWeek: 'Monday',
    instructorName: 'Prof. Sarah Jenkins',
    instructorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Lab C-102',
    status: 'upcoming',
  },
  {
    id: 's3',
    title: 'AI & Machine Learning Foundations',
    subject: 'Artificial Intelligence (AI)',
    timeFormatted: '02:00 PM - 03:30 PM',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    timeSlot: '02:00 PM - 03:30 PM',
    dayOfWeek: 'Tuesday',
    instructorName: 'Dr. Marcus Vance',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'AI Stream Hall 1',
    status: 'upcoming',
  },
  {
    id: 's4',
    title: 'Database Systems & SQL Lab Practice',
    subject: 'Information Technology (IT)',
    timeFormatted: '02:00 PM - 03:30 PM',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    timeSlot: '02:00 PM - 03:30 PM',
    dayOfWeek: 'Wednesday',
    instructorName: 'Prof. Elena Rostova',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Lab B-204',
    status: 'upcoming',
  },
  {
    id: 's5',
    title: 'Computer Networks & Cyber Security',
    subject: 'Cyber Security & Networking',
    timeFormatted: '10:00 AM - 11:30 AM',
    startTime: '10:00 AM',
    endTime: '11:30 AM',
    timeSlot: '10:00 AM - 11:30 AM',
    dayOfWeek: 'Thursday',
    instructorName: 'Dr. Alan Turing Jr.',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Security Lab 4',
    status: 'upcoming',
  },
  {
    id: 's6',
    title: 'Full-Stack Web Architecture & Cloud DevOps',
    subject: 'Information Technology (IT)',
    timeFormatted: '04:00 PM - 05:30 PM',
    startTime: '04:00 PM',
    endTime: '05:30 PM',
    timeSlot: '04:00 PM - 05:30 PM',
    dayOfWeek: 'Friday',
    instructorName: 'Dr. Marcus Vance',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Live Stream Room 3',
    status: 'upcoming',
  },
  {
    id: 's7',
    title: 'Open Source Development & Git Masterclass',
    subject: 'Computer Science (CS)',
    timeFormatted: '11:00 AM - 12:30 PM',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    timeSlot: '11:00 AM - 12:30 PM',
    dayOfWeek: 'Saturday',
    instructorName: 'Prof. David Lee',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    roomOrLink: 'Auditorium 2',
    status: 'upcoming',
  },
];

export const DEFAULT_LIVE_CLASSES: LiveClassItem[] = [
  {
    id: 'lc1',
    title: 'Data Structures & Algorithms Masterclass',
    subject: 'Computer Science (CS)',
    instructorName: 'Dr. Aris Thorne',
    instructorAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    timeFormatted: 'Today at 2:00 PM',
    isLive: true,
    attendanceCount: 42,
    bgGradient: 'from-[#1e1b4b] to-[#311b92]',
    progressPercent: 40,
    completedLessons: 6,
    totalLessons: 15,
  },
  {
    id: 'lc2',
    title: 'Artificial Intelligence & Neural Networks',
    subject: 'Artificial Intelligence (AI)',
    instructorName: 'Prof. Elena Rostova',
    instructorAvatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    timeFormatted: 'Tomorrow at 10:00 AM',
    isLive: false,
    attendanceCount: 38,
    bgGradient: 'from-[#0c4a6e] to-[#075985]',
    progressPercent: 80,
    completedLessons: 12,
    totalLessons: 15,
  },
  {
    id: 'lc3',
    title: 'Full-Stack Web Development & Cloud DevOps',
    subject: 'Information Technology (IT)',
    instructorName: 'Dr. Marcus Vance',
    instructorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    timeFormatted: 'Jan 26 at 4:30 PM',
    isLive: false,
    attendanceCount: 51,
    bgGradient: 'from-[#365314] to-[#1a2e05]',
    progressPercent: 20,
    completedLessons: 3,
    totalLessons: 15,
  },
];

export const DEFAULT_ASSIGNMENTS: AssignmentItem[] = [
  {
    id: 'a1',
    title: 'Data Structures & Algorithm Analysis Lab',
    subject: 'Computer Science (CS)',
    dueDate: 'Due in 2 days',
    status: 'in_progress',
    points: 100,
    type: 'assignment',
    isUrgent: true,
  },
  {
    id: 'a2',
    title: 'AI Neural Networks & Transformer Architectures Quiz',
    subject: 'Artificial Intelligence (AI)',
    dueDate: 'Due Jan 28',
    status: 'pending',
    points: 50,
    type: 'quiz',
    isUrgent: false,
  },
  {
    id: 'a3',
    title: 'SQL Database System Architecture & Practice Set',
    subject: 'Information Technology (IT)',
    dueDate: 'Completed Jan 20',
    status: 'completed',
    points: 100,
    type: 'practice_set',
    isUrgent: false,
  },
];
