import type {
  StudentBehaviorMetrics,
  StudentQuestionItem,
  AttendanceLogRecord,
} from '../types/progress.types';

export const DEFAULT_BEHAVIOR_METRICS: StudentBehaviorMetrics = {
  conductScore: 95,
  disruptionWarningsCount: 2,
  maxAllowedWarnings: 3,
  focusLevelPercent: 92,
  interactionQualityPercent: 88,
  lastIncidentNote: 'Warning issued on Aug 4 for asking non-topic gaming questions during live lecture. (2/3 warning chances used - 1 chance remaining before permanent account ban).',
  bannedMessage: 'ACCOUNT & EMAIL BANNED — Exceeded maximum 3/3 disruption warnings. Misbehavior is strictly not allowed in the app. Fines or payments are NOT accepted for misbehavior.',
};

export const DEFAULT_TEACHER_QUESTIONS: StudentQuestionItem[] = [
  {
    id: 'q-1',
    questionText: 'How does backpropagation update weights in deep neural networks?',
    topicName: 'Gradient Descent Optimization',
    timestampFormatted: 'Today, 10:15 AM',
    className: 'Advanced AI & Machine Learning',
    isRelevant: true,
    disruptionTag: 'relevant',
    teacherResponse: 'Great question! It computes partial derivatives using the chain rule.',
  },
  {
    id: 'q-2',
    questionText: 'What is the main difference between L1 and L2 regularization penalties?',
    topicName: 'Model Regularization',
    timestampFormatted: 'Yesterday, 02:40 PM',
    className: 'Data Science Fundamentals',
    isRelevant: true,
    disruptionTag: 'relevant',
    teacherResponse: 'L1 induces sparsity (Lasso), while L2 shrinks weights towards zero (Ridge).',
  },
  {
    id: 'q-3',
    questionText: 'Sir, which graphics card should I buy for playing 4K video games?',
    topicName: 'Unrelated Gaming Topic',
    timestampFormatted: 'Aug 04, 11:05 AM',
    className: 'Advanced AI & Machine Learning',
    isRelevant: false,
    disruptionTag: 'off_topic',
    teacherResponse: 'Warning 2 Issued: Please keep questions strictly focused on lecture topics during live class.',
  },
  {
    id: 'q-4',
    questionText: 'Can we use ReLU activation function in hidden layers of CNNs?',
    topicName: 'Convolutional Neural Networks',
    timestampFormatted: 'Aug 02, 09:30 AM',
    className: 'Deep Learning & Vision',
    isRelevant: true,
    disruptionTag: 'relevant',
    teacherResponse: 'Yes, ReLU is widely used as standard activation in CNN hidden layers.',
  },
  {
    id: 'q-5',
    questionText: 'Who is going to win the soccer match tonight?',
    topicName: 'Class Distraction',
    timestampFormatted: 'Jul 28, 03:15 PM',
    className: 'Data Science Fundamentals',
    isRelevant: false,
    disruptionTag: 'distraction',
    teacherResponse: 'Warning 1 Issued: Repeated off-topic comments distract the class session.',
  },
];

export const DEFAULT_ATTENDANCE_LOGS: AttendanceLogRecord[] = [
  {
    id: 'att-1',
    dateFormatted: 'Aug 08, 2026',
    className: 'Advanced AI & Machine Learning',
    subject: 'Neural Networks',
    status: 'absent',
    missedReason: 'Unexcused Absence (Missed 10:00 AM Session)',
  },
  {
    id: 'att-2',
    dateFormatted: 'Aug 04, 2026',
    className: 'Data Science Fundamentals',
    subject: 'Feature Engineering',
    status: 'absent',
    missedReason: 'Medical Leave Submitted',
  },
  {
    id: 'att-3',
    dateFormatted: 'Jul 29, 2026',
    className: 'Deep Learning & Vision',
    subject: 'CNN Architectures',
    status: 'absent',
    missedReason: 'Personal Emergency',
  },
  {
    id: 'att-4',
    dateFormatted: 'Jul 22, 2026',
    className: 'Python Data Structures',
    subject: 'Binary Trees & Graphs',
    status: 'absent',
    missedReason: 'Network Connectivity Issue',
  },
  {
    id: 'att-5',
    dateFormatted: 'Jul 15, 2026',
    className: 'Advanced AI & Machine Learning',
    subject: 'Supervised Learning',
    status: 'absent',
    missedReason: 'Unexcused Absence',
  },
  {
    id: 'att-6',
    dateFormatted: 'Aug 10, 2026',
    className: 'Advanced AI & Machine Learning',
    subject: 'Deep Learning',
    status: 'present',
  },
  {
    id: 'att-7',
    dateFormatted: 'Aug 09, 2026',
    className: 'Data Science Fundamentals',
    subject: 'Exploratory Analysis',
    status: 'present',
  },
  {
    id: 'att-8',
    dateFormatted: 'Aug 07, 2026',
    className: 'Python Data Structures',
    subject: 'Algorithmic Efficiency',
    status: 'present',
  },
];
