/**
 * Helper utility to trigger formatted text/HTML file downloads for PDF and Word DOCX formats in multiple languages (English, Urdu, Hinglish, Custom).
 */

export function downloadNoteAsPdf(
  title: string,
  content: string,
  formula?: string,
  language: string = 'English'
) {
  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]/gi, '_')}_${language.toLowerCase()}_notes.pdf`;
  const isRtl = language === 'Urdu';

  // Format content for printable PDF document
  const pdfHtml = `
    <!DOCTYPE html>
    <html lang="${isRtl ? 'ur' : 'en'}" dir="${isRtl ? 'rtl' : 'ltr'}">
      <head>
        <meta charset="utf-8" />
        <title>${title} (${language})</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #0F172A; line-height: 1.8; direction: ${isRtl ? 'rtl' : 'ltr'}; }
          h1 { color: #4F46E5; border-bottom: 2px solid #E2E8F0; padding-bottom: 10px; font-size: 24px; }
          .meta { font-size: 12px; color: #64748B; margin-bottom: 20px; text-transform: uppercase; font-family: monospace; }
          .lang-badge { display: inline-block; background: #E0E7FF; color: #4338CA; padding: 2px 8px; border-radius: 4px; font-weight: bold; margin-left: 8px; }
          .content { font-size: 15px; margin-bottom: 25px; white-space: pre-wrap; }
          .formula-box { background: #F1F5F9; border: 1px solid #CBD5E1; padding: 15px; border-radius: 8px; font-family: monospace; font-size: 16px; color: #059669; font-weight: bold; }
          .footer { margin-top: 50px; font-size: 11px; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 10px; }
        </style>
      </head>
      <body>
        <h1>${title} <span class="lang-badge">${language}</span></h1>
        <div class="meta">AI Physics Teacher • Generated Lecture Notes</div>
        <div class="content">${content}</div>
        ${formula ? `<div class="formula-box"><strong>Formula / فارمولا:</strong> ${formula}</div>` : ''}
        <div class="footer">Generated by AI Physics Classroom System • Language: ${language}</div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `;

  const blob = new Blob([pdfHtml], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.focus();
  } else {
    const a = document.createElement('a');
    a.href = url;
    a.download = safeFilename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }
}

export function downloadNoteAsDocx(
  title: string,
  content: string,
  formula?: string,
  language: string = 'English'
) {
  const safeFilename = `${title.toLowerCase().replace(/[^a-z0-9]/gi, '_')}_${language.toLowerCase()}_notes.docx`;

  const docxContent = `
================================================================================
AI PHYSICS TEACHER — LECTURE NOTES (${language.toUpperCase()})
================================================================================

TITLE: ${title}
LANGUAGE: ${language}

SUMMARY & CONTENT:
${content}

${formula ? `KEY FORMULA: ${formula}\n` : ''}
--------------------------------------------------------------------------------
Generated automatically by AI Physics Teacher Classroom
Date: ${new Date().toLocaleDateString()}
================================================================================
  `;

  const blob = new Blob([docxContent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = safeFilename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
