"""
apps/dashboard/constants/__init__.py
"""
from .search_constants import (
    DEFAULT_SEARCH_COURSES,
    DEFAULT_SEARCH_ASSIGNMENTS,
    DEFAULT_SEARCH_LIVE_CLASSES,
    DEFAULT_SEARCH_TOPICS,
    SEARCH_CACHE_TTL_SECONDS,
)

__all__ = [
    "DEFAULT_SEARCH_COURSES",
    "DEFAULT_SEARCH_ASSIGNMENTS",
    "DEFAULT_SEARCH_LIVE_CLASSES",
    "DEFAULT_SEARCH_TOPICS",
    "SEARCH_CACHE_TTL_SECONDS",
]
