# Generated by Django 6.0.6 - Classroom App Initial Migration
# This app owns: AI inference session storage only.
# Course/Assignment/LiveClass models live in apps.dashboard

from django.db import migrations


class Migration(migrations.Migration):
    """
    Classroom app initial migration.
    No database tables needed — classroom uses in-memory session storage
    and ChromaDB (non-relational). All ORM models belong to apps.dashboard.
    """

    initial = True

    dependencies = []

    operations = []
