# Generated by Django 6.0.6 on 2026-08-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('practice_set', 'Practice Set')], default='assignment', max_length=20)),
                ('points', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subject_field', models.CharField(db_index=True, max_length=100)),
                ('course_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('credit_hours', models.IntegerField(default=3)),
                ('progress_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('instructor_name', models.CharField(db_index=True, max_length=100)),
                ('time_formatted', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
