# Generated by Django 6.1.2 on 2026-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sessionattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('missed', 'Missed')], default='attended', max_length=16),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
