# Generated by Django 6.1.2 on 2026-10-08 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sessionattendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtimetable',
            name='reconciled_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('session_date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ends_at'], name='occurrence_user_end')],
                'constraints': [models.UniqueConstraint(fields=('user', 'session_id', 'session_date'), name='unique_session_occurrence')],
            },
        ),
    ]
