# Generated by Django 6.1.2 on 2026-10-08 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_savedtimetable_reconciled_through_sessionoccurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablejob',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetablejob',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetablejob',
            name='run_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='timetablejob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='planning_pending_jobs'),
        ),
    ]
