# Generated by Django 6.1.2 on 2026-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_timetablejob_attempts_timetablejob_next_attempt_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtimetable',
            name='next_reconciliation_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
